service: my-lambda-service
frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.9
  region: ${file(params/${opt:stage}/config.yml):region}
  timeout: 300
  role: ${file(params/${opt:stage}/config.yml):iam_role}
  environment:
    SRC_BUCKET: ${file(params/${opt:stage}/config.yml):src_bucket}
    DST_BUCKET_1: ${file(params/${opt:stage}/config.yml):dst_bucket_1}
    DST_BUCKET_2: ${file(params/${opt:stage}/config.yml):dst_bucket_2}
    DST_BUCKET_3: ${file(params/${opt:stage}/config.yml):dst_bucket_3}
    SNS_TOPIC_ARN: ${file(params/${opt:stage}/config.yml):sns_topic_arn}
    TOPIC_REGION: ${file(params/${opt:stage}/config.yml):region}
  tags:
    id: 2861
    name: demo-s3-copy
    created-by-email: msravanthi173@gmail.com

plugins:
  - serverless-prune-plugin
  - serverless-plugin-existing-s3
  - serverless-scriptable-plugin

custom:
  bucketName: ${file(params/${opt:stage}/config.yml):src_bucket}

  scriptHooks:
    after:deploy:deploy: |
      aws s3api put-bucket-notification-configuration \
        --bucket ${self:custom.bucketName} \
        --notification-configuration '{"EventBridgeConfiguration": {}}'

functions:
  copyFiles:
    name: ${opt:stage}-s3-copy-lambda-function
    handler: src.lambda_handler.lambda_handler
    events:
      - eventBridge:
          pattern:
            source:
              - "aws.s3"
            detail-type:
              - "Object Created"
            detail:
              bucket:
                name:
                  - ${file(params/${opt:stage}/config.yml):src_bucket}
