region: us-east-1
src_bucket: dev-src-bucket-1
dst_bucket_1: dev-dst-bucket-1
dst_bucket_2: dev-dst-bucket-2
dst_bucket_3: dev-dst-bucket-3
sns_topic_arn: arn:aws:sns:us-east-1:977965277372:s3Copy
tags:
  Environment: dev
  Owner: team-dev
